#!/usr/bin/env bash
# One-time WordPress setup via wp-cli. Idempotent: safe to run any number of times.
set -euo pipefail
cd /var/www/html

log() { echo "[wp-init] $*"; }

log "waiting for wp-config.php (generated by the wordpress container) ..."
until [ -f wp-config.php ]; do sleep 2; done

log "waiting for the database ..."
until php -r 'exit(@mysqli_connect(getenv("WORDPRESS_DB_HOST"), getenv("WORDPRESS_DB_USER"), getenv("WORDPRESS_DB_PASSWORD"), getenv("WORDPRESS_DB_NAME")) ? 0 : 1);' 2>/dev/null; do
  sleep 2
done

if ! wp core is-installed >/dev/null 2>&1; then
  log "installing WordPress ..."
  wp core install \
    --url="${WP_URL}" \
    --title="Example" \
    --admin_user=admin \
    --admin_password="${WP_ADMIN_PASSWORD}" \
    --admin_email=admin@example.invalid \
    --skip-email
fi

wp option update blogdescription "Prototype: OIDC access level at the edge" >/dev/null
wp option update timezone_string "Europe/Berlin" >/dev/null
wp rewrite structure '/%postname%/' >/dev/null
wp plugin is-active example-role >/dev/null 2>&1 || wp plugin activate example-role >/dev/null
wp plugin delete hello akismet >/dev/null 2>&1 || true

# Creates or updates a page from an HTML file. Prints the page ID as the last line.
ensure_page() {
  local slug="$1" title="$2" file="$3"
  local id
  id="$(wp post list --post_type=page --name="${slug}" --post_status=publish --field=ID | head -n1)"
  if [ -z "${id}" ]; then
    id="$(wp post create --post_type=page --post_status=publish --post_title="${title}" --post_name="${slug}" --post_content="$(cat "${file}")" --porcelain)"
    log "page '${title}' created (ID ${id})"
  else
    wp post update "${id}" --post_content="$(cat "${file}")" >/dev/null
    log "page '${title}' updated (ID ${id})"
  fi
  echo "${id}"
}

START_ID="$(ensure_page start "Start" /content/start.html | tail -n1)"
ensure_page members "Members area" /content/members.html >/dev/null

wp option update show_on_front page >/dev/null
wp option update page_on_front "${START_ID}" >/dev/null

log "done. Admin: ${WP_URL}/wp-admin/ (admin / ${WP_ADMIN_PASSWORD})"
